// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afdsowovqvmmjvumraxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmZHNvd292cXZtbWp2dW1yYXhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2OTc5OTIsImV4cCI6MjA2MzI3Mzk5Mn0.d11uatdlEDfhSlg6hPH-xfskZ3yNASr6DIPfGIdciVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);