// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrwcglmzrkomzivpbmwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhyd2NnbG16cmtvbXppdnBibXd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNjA2NDcsImV4cCI6MjA2MjkzNjY0N30.hw8aRfSIxAZ0AnYJ5XCDe68DKOFPYM8Qd-lrI6vcBN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);